### PR TITLE
Fix type params in Kleisli.md

### PR DESCRIPTION
**Pull request by ktonga**

### CODE REVIEW

**Comment by ktonga** [comment]
Hey @hrhino I do prefer `F` better too. Also it is used in the implementation so I tried to change all the `M`s with `F`s. Please double check.

Cheers.

**Comment by ktonga** [comment]
Yeah, you right. Lemme fix it.

**Comment by ktonga** [comment]
Did I miss any? otherwise ready to go.

**Comment by emilypi** [comment]
I'm on board with this. Thanks @ktonga

**Pull request merged**
