### PR TITLE
Add method Foldable#fold1Opt.

### PR DESCRIPTION
**Pull request by TomasMikula**
`fold1Opt` is to `fold` what `foldMap1Opt` is to `foldMap`.

### CODE REVIEW

**Comment by TomasMikula** [comment]
The failure is unrelated. Can someone please restart the build?

**Comment by puffnfresh** [comment]
So the error doesn't get lost:

```
[info] ! scalaz.concurrent.FutureTest.Future:not deadlock when using Nondeterminism#chooseAny: Exception raised on property evaluation.
[info] > Exception: java.lang.RuntimeException: Timeout occured, possible deadlock.
```

**Comment by TomasMikula** [comment]
It is green now.

**Comment by vmarquez** [comment]
👍

**Pull request merged**
