### PR TITLE
[8.0.x] example: Add Functor

### PR DESCRIPTION
**Pull request by NeQuissimus**

### CODE REVIEW

**Comment by TomasMikula** [comment]
I think we should at least mention the laws required to qualify as a functor.

**Comment by jdegoes** [comment]
Would be nice to show an example of using syntax for functor... assuming we have that in 8.

**Comment by NeQuissimus** [comment]
I added the laws and a usage example

**Comment by jdegoes** [comment]
@NeQuissimus Looks good, thanks!

**Pull request merged**
