### PR TITLE
Parallel `Applicative` transformers for `FreeT`.

### PR DESCRIPTION
**Pull request by Atry**
Given an `Applicative` for `F[A] @@ Parallel`, there should be an `Applicative` for `FreeT[S, F, A] @@ Parallel` available as well.

For example, this patch allows running a `FreeT[S, Task, ?]` in parallel, enabling Dependency Injection feature in a `Task`.

### CODE REVIEW

**Comment by wedens** [comment]
Isn't it basically `FreeApplicative`?

**Comment by Atry** [comment]
I don't think `scalaz.FreeAp` can provide similar functions:

``` scala
implicit def freeTParallelApplicative[S[_], F[_]](
  implicit FS: Functor[S],
  BF: BindRec[F],
  AF: Applicative[F],
  parallelApplicativeF: Applicative[Lambda[X => F[X] @@ Parallel]]
): Applicative[Lambda[X => FreeT[S, F, X] @@ Parallel]]
```

**Comment by Atry** [comment]
Any idea

**Comment by TomasMikula** [comment]
@Atry It seems to me that this parallel `ap(fa, ff)` will synchronize on corresponding occurrences of `F` in `fa` and `ff`, as if zipping them. This is in contrast to running both to completion and only synchronize at the end.

Also this `ap` introduces a bunch of pure `F`s in the result. As a consequence, if you then `ap` the result with something else, this second `ap` will synchronize on a lot of pure `F`s, thus many times one side of the parallel computation will do basically nothing.

Maybe you want to consider using`FreeAp[Free[S, F, ?], A]` instead?

**Comment by Atry** [comment]
@TomasMikula Do you mean `FreeAp[FreeT[S, F, ?], A]` ?

**Comment by TomasMikula** [comment]
Yeah, fixed the typo. Wouldn't that work better for you?

**Comment by Atry** [comment]
Yes. `FreeAp[FreeT[S, F, ?], A]` looks good?

Do you think we should add Monad transformers for `FreeAp`?

**Comment by TomasMikula** [comment]
I'm not exactly sure what you mean by that.

But `FreeApT[S[_], F[_], A]`, a transformer version `FreeAp[S[_], A]`, could be useful.

**Comment by Atry** [comment]
I wonder if `FreeAp[F[_], A]` itself could be a transformer, forwarding type class calls to `F`.

**Comment by Atry** [comment]
The behavior is:
  * Creating a lazy AST for `ap` and all other `Applicative` methods
  * Forwarding `flatMap` and other `Monad` calls that beyond `Applicative` to `F` immediately

**Comment by TomasMikula** [comment]
Yeah, OK, I think that makes sense 👍

**Pull request closed without merging**
