### PR TITLE
Add mapF in analogy to flatMapF to Monad Transformers

### PR DESCRIPTION
**Pull request by justjoheinz**
Given map(A => B) and flatMapF(A => G[F[B]) we should have mapF(A => G[B])
I also fixed an anomaly in the flatMapF signature of OptionT compared to the other transformers.
I also added a show instance for MaybeT.
This would break existing code, please review carefully.

### CODE REVIEW

**Comment by jedws** [comment]
seems like there's an interface these could implement to guarantee consistency, something like

/**
     * Standard interface for monad transformers
     * 
     * F is what a transformer is parameterised by
     * M is the underlying type being transformed
     * T is the transformer type itself (F-bound)
     * A is the contained type
     */
    trait MonadTransformer[F[_], M[_], T[_[_], _], A] {
      def mapF[X](f: A => X): T[F, X]
      def flatMapF[X](f: A => F[M[X]])(implicit F: Monad[F]): T[F, X]
    }

I don't know if this is valuable or not.

**Comment by justjoheinz** [comment]
I did not do something like that, since currently not all Monad Transformers implement something like flatMapF. I only added mapF (which would be `def mapF[X](f: A => F[X]): T[F, X]` for transformers which already provided flatMapF.

But describing these functions in a trait would have avoided the problem of the misaligned implemention of flatMapF in OptionT of course.

**Comment by vmarquez** [comment]
:+1:

@justjoheinz if you can get another +1 I'll merge.  Thanks.

**Comment by justjoheinz** [comment]
Anything I can do, do get this into master?

**Comment by TomasMikula** [comment]
This method, unlike `flatMapF`, indeed seems to have a uniform implementation for any monad transformer:

```scala
trait MonadTrans[F[_[_], _]] {
  def liftM[G[_] : Monad, A](a: G[A]): F[G, A]

  implicit def apply[G[_] : Monad]: Monad[F[G, ?]]

  def mapF[G[_], A, B](fa: F[G, A])(f: A => G[B])(implicit M: Monad[G]): F[G, B] =
    Monad[F[G, ?]].bind(fa)(a => liftM(f(a)))
}
```

(Maybe a better name here would be `mapM` for consistency with `liftM`.)

**Comment by justjoheinz** [comment]
Ok, I see that I can get this implemented. flatMapF should work as well, as the current diverging implementations are inconsistent.

**Comment by TomasMikula** [comment]
@justjoheinz I don't see how you could implement `flatMapF` uniformly, without knowing the implementation details of individual data types. It seems to me that `flatMapF` is there for data types that are just wrappers around other data types, and `flatMapF(f)` is like `flatMap(f)`, except it allows `f` to return an unwrapped value. In a generic setting, it is impossible to tell what the unwrapped type for `T[F, A]` is (or that `T` is a wrapper type at all).

**Pull request merged**
