### PR TITLE
[A,B] (NonEmptyList[A] ⇒ B) ⇒ List[A] ⇒ Option[B]

### PR DESCRIPTION
**Pull request by refried**

### CODE REVIEW

**Comment by xuwei-k** [comment]
please squash commits

**Comment by S11001001** [comment]
:+1:

**Comment by tonymorris** [comment]
:+1:

I lyk.

**Comment by xuwei-k** [comment]
merged in https://github.com/scalaz/scalaz/commit/ba42bccd67e95dd62347c361ccb061d783522d26

**Pull request closed without merging**
