### PR TITLE
MonadPlus and Traverse instances for Dequeue (Backport of #1566)

### PR DESCRIPTION
**Pull request by Jacoby6000**
I see now that on my previous PR (#1567) I just forgot to set the base branch, but I've already deleted those changes under the assumption that I nuked the history.  Whoops.

### CODE REVIEW

**Comment by Jacoby6000** [comment]
I saw that, but `Traverse` extends `Foldable`, so I thought it was a false alarm.  What needs to be done?

**Comment by xuwei-k** [comment]
I think mima is right.

- https://github.com/xuwei-k/scalaz-1568/commit/4eeb8ac2cfa10bd2752e355d4a8fb5b798cca255
- https://travis-ci.org/xuwei-k/scalaz-1568/builds/314543756

**Comment by xuwei-k** [comment]
https://github.com/xuwei-k/scalaz/commit/fea539d9256e971fd870fc29277ae4ea4b6df625

**Comment by Jacoby6000** [comment]
I've merged in your changes and that seems to have fixed the problem. Thanks for testing it and providing a solution!

**Pull request merged**
