### PR TITLE
deprecate all the unsafe methods on Future/Task

### PR DESCRIPTION
**Pull request by jedws**
and have them call newly named `unsafePerform*` variants

### CODE REVIEW

**Comment by puffnfresh** [comment]
Is it always unsafe to run a Task?

**Comment by jedws** [comment]
@puffnfresh wdym? `1.point[Task].unsafePerformSync` is safe, is that what you mean?

**Comment by tpolecat** [comment]
In practice `.run` is unsafe in exactly the same way `.unsafePerformIO` is unsafe. My impr.ession is that `Task` has subsumed `IO` for most users

**Comment by jedws** [comment]
@tpolecat exactly, but it is called `.run` which is the same as the nice and safe `run` on many of the functional data structures (eg.`Kleisli`).

**Comment by vmarquez** [comment]
I like this change, but I do think methods like attemptRun and runAsync should somehow be marked as *more* unsafe than than the bounded (time wise) ones.  Thoughts @jedws  ?

**Comment by jedws** [comment]
@vmarquez I'm not sure that "more unsafe" is much use to signify, or how you'd go about signifying it (`reallyUnsafe*` ?). With this change, we are simply trying to distinguish between the things that release the rockets and the pure API.

Perhaps another PR could add more documentation or something, but a

**Comment by wedens** [comment]
:+1:

**Comment by xuwei-k** [comment]
What is the status of this? I don't have a strong opinion this, but it's about time I want to release `7.2.0-RC1` and `7.2.0 final`.

**Comment by tpolecat** [comment]
:+1: I would like to get this in for 7.2 if we can.

**Comment by jedws** [comment]
@xuwei-k I've been waiting for others to opine and maybe merge, I really want to see it in 7.2

**Pull request merged**
