### PR TITLE
Remove variance from almost everything and introduce variance typeclasses

### LINKED ISSUE #1892: remove all covariant / contravariant type parameters
there was a good stab at this already, but there are still some data types that are using `+` / `-` type parameters.

### PR DESCRIPTION
**Pull request by hrhino**
Also, some cleanup around `StreamT` to use an ADT rather than some weird abstract class stuff. I'll do more later.

The `IsCovariant` and `IsContravariant` typeclasses are @alexknvl's work.

This is a little beyond my ken in places, so please let me know if any of this is egregiously mistaken.

Closes #1892.

### CODE REVIEW

**Comment by hrhino** [comment]
Because i'm lazy. I'll pull the `StreamT` out when I have time to get back to this.

**Comment by emilypi** [comment]
@hrhino ping

**Comment by ysusuk** [comment]
it the last thing missing here is to take `StreamT` out?

**Comment by emilypi** [comment]
@ysusuk lets get @hrhino's opinion. I'll see if i can get him to comment

**Pull request merged**
