### PR TITLE
Add StreamT.weakMemoize

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
Blocked by https://github.com/scala-js/scala-js/pull/4617

**Comment by Atry** [comment]
`EphemeralStream.weakMemo` is not yet support Scala.js. However we didn't have a test running `weakMemo`.

**Comment by armanbilge** [comment]
FYI you can use this project https://github.com/scala-js/scala-js-weakreferences/. I don't think they can accept that PR to core for historical reasons.

**Comment by Atry** [comment]
Added the dependency to fix the test

**Comment by Atry** [comment]
It's an optional dependency so it would not automatically introduce the dependency for scalaz users

**Comment by Atry** [comment]
Rebased to trigger CI

**Pull request merged**
