### PR TITLE
Resolve ambiguous implicits for Scala 2.13.0-M3

### PR DESCRIPTION
**Pull request by joroKr21**
In preparation. There may be more but this is what the tests caugth.

### CODE REVIEW

**Comment by joroKr21** [comment]
Diff is awful at showing methods that just moved around...

**Comment by xuwei-k** [comment]
I think we should wait Scala 2.13.0-M3 release.

**Comment by adriaanm** [comment]
I just promoted M3 to maven :-)

**Comment by xuwei-k** [comment]
I just fixed some errors in https://github.com/scalaz/scalaz/commit/c4141cd7ca8f74db49efa223ba9ae353efe5f98d

I'm not sure whether some changes necessary 🤔 
(e.g. Endomorphic, Free.Sink, Free.Source, IdT, Kleisli, LazyEitherT, OneOr, TheseT ...)

**Comment by joroKr21** [comment]
Feel free to pick up fixes from this PR. The other changes are needed for the tests.

**Comment by xuwei-k** [comment]
https://github.com/scala/bug/issues/10706 😕

**Pull request merged**
