### PR TITLE
plusA on Applicative (#1984)

### PR DESCRIPTION
**Pull request by gaelrenoux**
PR for issue #1984, with help from @jdegoes

### CODE REVIEW

**Comment by gaelrenoux** [comment]
I discovered there was an older PR for this ticket, but it seems to be abandoned, and it didn't have the appendM on Applicative. I integrated more tests after reading the reviews on that PR.

**Comment by psilospore** [comment]
Oh it's not abandoned. I completed the requested changes on that PR. I've just been waiting for a response.

**Comment by gaelrenoux** [comment]
Sorry, misclick

**Comment by hrhino** [comment]
LGTM. I took the liberty of renaming the PR to reflect the name `plusA`.

**Comment by hrhino** [comment]
Thanks!

**Comment by emilypi** [comment]
Nie, thanks @hrhino 😄

**Pull request merged**
