### PR TITLE
Start some backports

### PR DESCRIPTION
**Pull request by Blaisorblade**
Backport (via cherry-pick) 4a16dc3, 87a55c3 (that is, #643) and 8b15807 from #665 (some of the first ones, randomly picked).

I did this in the weekend, and some patches would deserve a closer look, because they were basically "change all instances of X", and my backport is "change all instances of X from 7.1.x which are still in 7.0.x".

### CODE REVIEW

**Comment by aloiscochard** [comment]
I would be surprised if anyone still care about backporting those?

If yes please re-open.

**Comment by Blaisorblade** [comment]
Closing is OK, thanks.

**Comment by xuwei-k** [comment]
I'm working on backporting to 7.0.x branch. I will send new pull request within a few days.

**Comment by aloiscochard** [comment]
@xuwei-k great! ty

**Pull request closed without merging**
