### PR TITLE
[8.0.x] Convert example module to use tut

### PR DESCRIPTION
**Pull request by NeQuissimus**
Related to #1526 

I took `Forall` as a first example, the code there was pretty good already.
`Maybe` and `Maybe2` should probably be rewritten/expanded upon.

I chose to make `example` a regular module without cross building since we really only need to generate documentation once.

I also updated SBT because I was encountering the bug where you can't exit SBT after a while, except by killing the process (I can't find the issue right now but it was fixed in 1.0.2 IIRC). Anyways, updating SBT should not hurt us...

I will add the content from #1521 once it has been merged.

This is what `sbt example/tut` generates:

---

# Forall

## Instance creation

Create instance using `of` or `mk`

```scala
scala> import scalaz.Prelude._
import scalaz.Prelude._

scala> val nil: ∀[List] = ∀.of[List](Nil)
nil: scalaz.Prelude.∀[List] = List()

scala> val emptyMap: ∀∀[Map] = ∀∀.of[Map](Map())
emptyMap: scalaz.Prelude.∀∀[Map] = Map()

scala> val nil1: ∀[List] = ∀.mk[∀[List]].from(Nil)
nil1: scalaz.Prelude.∀[List] = List()

scala> val emptyMap1: ∀∀[Map] = ∀∀.mk[∀∀[Map]].from(Map())
emptyMap1: scalaz.Prelude.∀∀[Map] = Map()
```

## Universally quantified Semigroup

```scala
scala> import scalaz.Prelude._
import scalaz.Prelude._

scala> import scalaz.typeclass.Semigroup
import scalaz.typeclass.Semigroup

scala> def listSemigroup[A]: Semigroup[List[A]] = new Semigroup[List[A]] {
     |   def append(x: List[A], y: => List[A]) = x ++ y
     | }
listSemigroup: [A]=> scalaz.typeclass.Semigroup[List[A]]

scala> type Plus[F[_]] = ∀[λ[A => Semigroup[F[A]]]]
defined type alias Plus

scala> val listPlus: Plus[List] = ∀.mk[Plus[List]].from(listSemigroup)
listPlus: Plus[List] = $anon$1@4fd9f447

scala> listPlus[Int].append(List(1, 2), List(3, 4)) == List(1, 2, 3, 4)
res0: Boolean = true
```

## Natural transformation

```scala
scala> import scalaz.Prelude._
import scalaz.Prelude._

scala> type ~>[F[_], G[_]] = ∀[λ[A => F[A] => G[A]]]
defined type alias $tilde$greater

scala> val headOption: List ~> Option = ∀.mk[List ~> Option].from(_.headOption)
headOption: List ~> Option = $$Lambda$5445/1776413731@66971edd

scala> headOption[Int](List(1, 2, 3)) == Some(1)
res1: Boolean = true

scala> implicit class NaturalTransformationOps[F[_], G[_]](trans: F ~> G) {
     |   def $(f: ∀[F]): ∀[G] = ∀.of[G](trans.apply.apply(f.apply))
     | }
defined class NaturalTransformationOps

scala> val none: ∀[Option] = headOption $ nil
none: scalaz.Prelude.∀[Option] = None
```

## Binatural transformation

```scala
scala> type ~~>[F[_, _], G[_, _]] = ∀∀[λ[(α, β) => F[α, β] => G[α, β]]]
defined type alias $tilde$tilde$greater

scala> type Option2[A, B] = Option[(A, B)]
defined type alias Option2

scala> val pick: Map ~~> Option2 = ∀∀.mk[Map ~~> Option2].from(_.headOption)
pick: Map ~~> Option2 = $$Lambda$5447/774572479@50241511

scala> pick[String, Int](Map("hi" -> 5)) == Some("hi" -> 5)
res2: Boolean = true

scala> implicit class BinaturalTransformationOps[F[_, _], G[_, _]](trans: F ~~> G) {
     |   def $(f: ∀∀[F]): ∀∀[G] = ∀∀.of[G](trans.apply.apply(f.apply))
     | }
defined class BinaturalTransformationOps

scala> val none2: ∀∀[Option2] = pick $ emptyMap
none2: scalaz.Prelude.∀∀[Option2] = None
```

### CODE REVIEW

**Comment by TomasMikula** [comment]
Thanks!

We should make sure that tut is run by travis.

**Comment by NeQuissimus** [comment]
@jdegoes tweeted something about getting the 8.0.x branch to start building and publishing, so I am touching the build as little as I could...
If you'd rather I hook tut into the travis build already, I can do that... Somebody with commit access and better knowledge of publishing with sbt will need to actually put the tut output somewhere, though.

**Comment by TomasMikula** [comment]
Currently the build ensures that PRs don't break examples. I don't want to lose this check.

**Comment by NeQuissimus** [comment]
I made things a little fancier by adding [sbt-microsites](https://github.com/47deg/sbt-microsites) on top of `tut`.

Here is what the current build looks like: http://nequissimus.com/scalaz/index.html

**Comment by NeQuissimus** [comment]
What does it take for us to merge this? I'd like to add PRs that are based on this :) (Add examples for other types)

**Comment by jdegoes** [comment]
@NeQuissimus Done! All you had to do was commit to more PRs and I was sold. 😉

**Comment by NeQuissimus** [comment]
@jdegoes 😄 Don't worry, I'll be around for as long as I do Scala at my job (or maybe do worry xD)

**Comment by jdegoes** [comment]
@NeQuissimus You better be!

Maybe since we're using `tut` it makes sense to go full sbt microsites?

**Comment by NeQuissimus** [comment]
@jdegoes That's what I did!
Check this out: http://nequissimus.com/scalaz/index.html (just a deployment of the example project)

**Pull request merged**
