### PR TITLE
Issue 1816 - Adopt modern file naming convention

### PR DESCRIPTION
**Pull request by barambani**
this is for https://github.com/scalaz/scalaz/issues/1816

### CODE REVIEW

**Comment by jdegoes** [comment]
@barambani This change makes me so happy! 😄

**Comment by jdegoes** [comment]
@barambani A few conflicts to resolve, too.

**Comment by barambani** [comment]
sure, I'm on them :)

**Comment by jdegoes** [comment]
@barambani 

Looking much better! I just saw the following remaining:

```
ct/Endo.scala
ct/Iso.scala
ct/Kleisli.scala
types/As.scala
types/Is.scala
types/Leibniz.scala
types/Liskov.scala
types/NotIs.scala
core/Void.scala
```

**Comment by barambani** [comment]
That was a strange problem with git, fixing it

**Comment by jdegoes** [comment]
@barambani This looks great! There are a few conflicts due to other changes with master, can you resolve and I'll get this merged in?

**Comment by barambani** [comment]
sure, I'll take care of that 👍

**Comment by jdegoes** [comment]
@barambani Looks great! Thanks. 😄

**Pull request merged**
