### PR TITLE
Remove unnecessary implicit parameter Applicative[S] in Free.suspend

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
@xuwei-k Could you review this PR please?

**Comment by Atry** [comment]
Any idea? @xuwei-k @S11001001 @TomasMikula

**Comment by TomasMikula** [comment]
Good catch on the unnecessary `Applicative`!

As for the caching, I would at least localize the `asInstanceOf` more, such as

```scala
@inline private def pointUnit[S]: Free[S, Unit] = pointUnitCache.asInstanceOf[Return[S, Unit]]
```

**Comment by Atry** [comment]
@TomasMikula `pointUnit` done.

**Pull request merged**
