### PR TITLE
Add -opt:l:method when compiling with Scala >=2.12

### PR DESCRIPTION
**Pull request by S11001001**
Addresses #1292.

### CODE REVIEW

**Comment by S11001001** [comment]
Well, that's not what you'd like to see.

```
java.lang.IllegalArgumentException
	at scala.tools.asm.ClassReader.<init>(ClassReader.java:170)
	at scala.tools.asm.ClassReader.<init>(ClassReader.java:153)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.$anonfun$parseClass$1(ByteCodeRepository.scala:274)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.parseClass(ByteCodeRepository.scala:272)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.parsedClassNode(ByteCodeRepository.scala:83)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.classNode(ByteCodeRepository.scala:108)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.findInSuperClasses$1(ByteCodeRepository.scala:192)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.$anonfun$methodNode$12(ByteCodeRepository.scala:257)
	at scala.tools.nsc.backend.jvm.opt.ByteCodeRepository.methodNode(ByteCodeRepository.scala:256)
	at scala.tools.nsc.backend.jvm.opt.CallGraph.$anonfun$addMethod$1(CallGraph.scala:131)
	at scala.tools.nsc.backend.jvm.opt.CallGraph.$anonfun$addMethod$1$adapted(CallGraph.scala:128)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.tools.nsc.backend.jvm.opt.CallGraph.addMethod(CallGraph.scala:128)
	at scala.tools.nsc.backend.jvm.opt.CallGraph.$anonfun$addClass$1(CallGraph.scala:87)
	at scala.tools.nsc.backend.jvm.opt.CallGraph.$anonfun$addClass$1$adapted(CallGraph.scala:87)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.tools.nsc.backend.jvm.opt.CallGraph.addClass(CallGraph.scala:87)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.$anonfun$runGlobalOptimizations$2(GenBCode.scala:239)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.$anonfun$runGlobalOptimizations$2$adapted(GenBCode.scala:237)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.runGlobalOptimizations(GenBCode.scala:237)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker2.run(GenBCode.scala:257)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.buildAndSendToDisk(GenBCode.scala:384)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:350)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1418)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1403)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1398)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1492)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
```

**Comment by xuwei-k** [comment]
Maybe Java9 specific issue. This issue will fix Scala 2.12.2
- https://github.com/scala/scala-asm/commit/ccbe1cad9c27303043f43bce16dda948e3285fff
- https://github.com/scala/scala/commit/8136057e7c4a403433fd4c66b32de7df972029fe

**Comment by xuwei-k** [comment]
Scala 2.12.2 released and I just updated https://github.com/scalaz/scalaz/commit/74bccf5079f0a96769cd4a93ddd9209f82321757

**Comment by S11001001** [comment]
Works with 2.12.2, @xuwei-k

**Pull request merged**
