### PR TITLE
 Add Zap instance for pairs of Zaps

### PR DESCRIPTION
**Pull request by japgolly**

### CODE REVIEW

**Comment by jdegoes** [comment]
This looks nice. It'd be great to have an example added to the examples that shows Scala can actually locate this instance when required.

**Comment by emilypi** [comment]
If this builds, I'll merge

**Comment by japgolly** [comment]
Ah yeah thanks. The intent to add an example is there but realistically
I'll probably never get around to it. Even this PR looks trivial but the
same thing seemed profound when I saw it expressed as pairing rather than
zap.

**Comment by emilypi** [comment]
@japgolly do you want me to just close it then? I'm good _without_ an example

**Comment by japgolly** [comment]
If you're good to merge, I think it should be merged. Lots of things in
scalaz are useful without being profound :)

**Pull request merged**
