### PR TITLE
Make *> non-strict in its second argument.

### PR DESCRIPTION
**Pull request by kevinmeredith**
Addresses #1020.

## Testing

I also added a few unit tests within this PR.

```
Welcome to Scala version 2.10.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).

import scalaz.syntax._
import scalaz.Scalaz._

scala> none[Int] *> ???
res1: Option[Nothing] = None
```

### CODE REVIEW

**Comment by kevinmeredith** [comment]
I don't know against which branch this PR should apply.

So please correct me if wrong.

**Comment by vmarquez** [comment]
Thanks for the PR.  Couple things.  Is this always desirable?  Any previous discussion on why it was done this way?  And finally, this may have some performance impacts... 

I suspect some others may have strong feelings on this @puffnfresh  etc.

**Comment by tonymorris** [comment]
It's not always desirable. You need (2^n) versions of every function for which there are n arguments for every combination of strict and non-strict argument. This is of course, silly. So just write the subset of those functions which are useful.

It is not a good idea in Scala to argue over whether a function argument should, or should not, be strict. Make both versions. The function being proposed here is useful, so it should be written in addition to the existing useful function that already exists.

Scala does not do non-strictness well. It is best to concede to that fact, and accept this outcome imo.

**Comment by kevinmeredith** [comment]
Thanks for the review, Vincent and Tony.

I'm not sure how to implement two versions of `*>`, i.e. where the second argument is call by name and by value. I attempted to do so via this example:

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

def f(x: => Int) = 42
def f(x: Int) = 66

// Exiting paste mode, now interpreting.

f: (x: => Int)Int <and> (x: Int)Int
f: (x: => Int)Int <and> (x: Int)Int

scala> f( {println("hi!"); 1 } )
hi!
res3: Int = 66
```

I'm guessing that overloading is not possible in this case?

Thanks

**Comment by tonymorris** [comment]
Just name it something else.

**Comment by kevinmeredith** [comment]
OK - I added `*>'`, reverting any changes to `*>`.

I'm not familiar with this library's naming conventions, so please let me know if it's OK.

**Comment by puffnfresh** [comment]
I don't think it's practical for the identifier to have a `'` in it.

**Comment by tonymorris** [comment]
I honestly don't know a solution to the explosion of a naming problem. All I know is that debating the strictness of a function argument, for scala, is not a good idea. Both sides of the debate win; produce two functions [then repeat].

**Comment by tpolecat** [comment]
N.B. I recently learned that `fooʹ` is and always has been a valid identifier, you just have to know how to type the correct `ʹ` (U+02B9). However it's considered alpha so `*>ʹ` isn't valid.

**Comment by kevinmeredith** [comment]
Please offer an alternative, @puffnfresh, and I will change it.

**Comment by tonymorris** [comment]
You could come up with a naming scheme where `ʹ` denotes the strictness of arguments.

Clutching at straws I know.

**Comment by kevinmeredith** [comment]
> You could come up with a naming scheme where `ʹ` denotes the strictness of arguments.

Is there any existing naming schema that differentiates strict from non-strict functions?

**Comment by tonymorris** [comment]
Nothing I know of. Be the first!

**Comment by kevinmeredith** [comment]
I'm going to check this [thread](https://groups.google.com/forum/#!topic/scala-user/SkjN0l9mXCk) over the next day or less. 

Then, I'll update this PR with my proposed re-name!

**Comment by TomasMikula** [comment]
When naming higher-kinded versions of a thing, names like `Functor`, `FunctorK`, `FunctorKA` `HFunctorK`, etc. got confusing very quickly. I'm now using names like

```scala
`Functor{* -> *}`
`Functor{(* -> *) -> *}`
`Functor{(* -> *) -> * -> *}`
```
Slightly longer, but this scheme scales to any kinds.

Similarly, you might want to have a scheme that scales to any number of arguments.

**Comment by tonymorris** [comment]
@TomasMikula somewhere in the scalaz history you'll find a similar naming scheme but for a different purpose: applying type constructors of a different kind. It also went through a stage of naming like `Apply1Of2`, but that doesn't work when the type constructor accepts type constructor arguments.

@kevinmeredith You are very brave asking [scala-user] for advice on naming schemes. Good luck!

**Comment by kevinmeredith** [comment]
Rex Kerr shared his [experiences](https://groups.google.com/d/msg/scala-user/SkjN0l9mXCk/tOqk-M8XCwAJ) with such a naming convention.

But I'm not sure if you care for the `*>ByName` (surrounded by ticks), per Rex's comments.

**Comment by tonymorris** [comment]
Told ya asking [scala-user] is a brave move :)

You still have the problem of multiple arguments and each combination of strictness.

**Comment by kevinmeredith** [comment]
> You still have the problem of multiple arguments and each combination of strictness.

I see. However, would you ever want to call `*>`'s first argument in a non-strict fashion?

**Comment by tonymorris** [comment]
Yep. You asking me to come up with an example?

**Comment by kevinmeredith** [comment]
Please! I am asking for my own understanding.

**Comment by kevinmeredith** [comment]
@S11001001 for the `<*` variant, you're expecting that the left argument is evaluated non-strictly?

Example:

```scala
??? `<*ByName` none[Int] 
```

would result in `None` rather than throw since the right argument short-circuited?

If so, would that require changing [self](https://github.com/scalaz/scalaz/blob/series/7.3.x/core/src/main/scala/scalaz/syntax/ApplySyntax.scala#L5) to be evaluated in a call by-name fashion?

```
final class ApplyOps[F[_],A] private[syntax](val self: => F[A]) ...
```

**Comment by S11001001** [comment]
@kevinmeredith No, left-strict, right-non for both `*>` and `<*`.

**Comment by kevinmeredith** [comment]
Understood, @S11001001. I believe that my last commit addresses your requested changes.

**Comment by TomasMikula** [comment]
A bit of bikeshedding regarding `ʹ` (U+02B9): There is a similar-looking letter in the same unicode block, `ˊ` (U+02CA):

| Code | Glyph | `monospace` glyph | Description |
| --- | --- | --- | --- |
| U+02B9 | ʹ | `ʹ` | Modifier Letter Prime |
| U+02CA | ˊ | `ˊ` | Modifier Letter Acute Accent |

The word "acute" might better convey the meaning (i.e. strictness) than the word "prime".

The monospaced glyph for Acute Accent doesn't look very good here on GitHub, but in both my IntelliJ and vim (with default fonts) it is better discernible from `'` than the Prime symbol.

**Pull request merged**
