### PR TITLE
make an enum for a jenum

### PR DESCRIPTION
**Pull request by merlinorg**
Provides Enum typeclass evidence for Java enum types. #1449

### CODE REVIEW

**Comment by fommil** [comment]
oh awesome!

**Comment by fommil** [comment]
if this is backcompat it can target 7.2

**Comment by merlinorg** [comment]
@fommil this new instance requires implicit classtag evidence so isn't binary compatible with 7.2. i will provide a 7.2 pr if i can get mima to smile upon me.

@xuwei-k the equal instances in js and native have been restored.

**Comment by xuwei-k** [comment]
backported to 7.2 https://github.com/scalaz/scalaz/commit/49e1c828604dc66912a9c1ac0a168ce49a366c2f

**Pull request merged**
