### PR TITLE
Add method Order#sort(x, y).

### PR DESCRIPTION
**Pull request by TomasMikula**

### CODE REVIEW

**Comment by gpampara** [comment]
:-1:

**Comment by tonymorris** [comment]
@gpampara why?

**Comment by TomasMikula** [comment]
The motivation for this method is to reduce the use of `if`/`else` in the user code, because it is prone to errors by accidentally swapping the `if` and `else` branches. This is due to the fact that a boolean test (e.g. `Order#lessThan(x, y)`) is "forgetful": the result (a boolean value) bears no connection to the tested values, and thus in order to do anything useful with the result of the test, you have to reach back to the tested values in the `if` and `else` branches, and this is very easy to mismatch.

Therefore, I think it is good practice to try to push `if`/`else` down to the most basic operations (such as the implementation of the proposed `sort` method) and compose higher level code from these basic operations (without additional `if`s if possible).

**Comment by S11001001** [comment]
I like it. :+1:

**Comment by gpampara** [comment]
Upon looking at this again, I'm not sure what I was thinking.... Sorry for the noise! :+1:

**Pull request merged**
