### PR TITLE
Associative type-class

### PR DESCRIPTION
**Pull request by puffnfresh**
I was planning on adding more instances but I'm making a pull request in case anyone else can help out before I get to it.

The class is something like this:

```scala
trait Associative[=>:[_, _]]  {
  def reassociateLeft[A, B, C](f: A =>: (B =>: C)): (A =>: B) =>: C
  def reassociateRight[A, B, C](f: (A =>: B) =>: C): A =>: (B =>: C)
}
```

The laws are:

```
reassociateLeft . reassociateRight = id
reassociateRight . reassociateLeft = id
```

Instances:

* [x] Tuple2
* [x] LazyEither
* [x] LazyTuple
* [x] \/
* [x] Either
* [x] Validation

### CODE REVIEW

**Comment by xuwei-k** [comment]
:+1:

**Comment by aloiscochard** [comment]
Here is the rest:
https://github.com/puffnfresh/scalaz/pull/2

I did it quickly hope I didn't miss something!

**Comment by puffnfresh** [comment]
@relrod @aloiscochard: brilliant stuff :heart:

**Comment by relrod** [comment]
:+1:

**Pull request merged**
