### PR TITLE
IList groupBy uses NonEmptyList instead of IList

### PR DESCRIPTION
**Pull request by adelbertc**

### CODE REVIEW

**Comment by adelbertc** [comment]
API-breaking change, not really a drop-in for `scala.collection.immutable.List` by using `NonEmptyList` as opposed to `IList` - could keep the old one and have a `groupBy1` as well.

**Comment by vmarquez** [comment]
My two cents are that as a library user,  I'm fine with breaking changes that can be fixed with a single method call (NEL.list -> IList)

**Comment by tpolecat** [comment]
Looks good to me, only question is whether we want a deprecation cycle with the old one.

**Comment by tpolecat** [comment]
Any reason this isn't on `Foldable`?

**Pull request merged**
