### PR TITLE
StreamT#foldLeft stack safety

### PR DESCRIPTION
**Pull request by TomasMikula**
This PR contains a fix for #1123 by making the arguments of `foldLeft` by-value.

### CODE REVIEW

**Comment by vmarquez** [comment]
I like this change. 👍once you fix the merge issues.  We will need one more review before we merge though.  @xuwei-k ?

**Comment by TomasMikula** [comment]
Merge issues? I don't seem to see any.

**Comment by vmarquez** [comment]
@TomasMikula GH says it is out of date and doesn't let someone merge until you update your branch with the latest from 7.3.x

**Comment by TomasMikula** [comment]
Alright, done. I didn't think this would be necessary unless there was a merge conflict (which there is not).

**Comment by TomasMikula** [comment]
Could someone please restart the build?

**Comment by xuwei-k** [comment]
merged 
- https://github.com/scalaz/scalaz/commit/ef0a25634d665bc86e138d2406020328e84f4759
- https://github.com/scalaz/scalaz/commit/8af02a59ea5896e3349ede74f55270bcab4dfa02
- https://github.com/scalaz/scalaz/commit/9c98d1f9a64f237f9b72193d241afab5692a8508

**Pull request closed without merging**
