### PR TITLE
added some functions in IO

### PR DESCRIPTION
**Pull request by wi101**

### CODE REVIEW

**Comment by jdegoes** [comment]
👍🙏 Very helpful! Thanks. :)

**Comment by wi101** [comment]
with pleasure :) 
travis fails because of `scalafmtCheck` I don't know how can I solve that problem?

**Comment by jdegoes** [comment]
Run from sbt the following command:

compile:scalafmt

**Comment by ktonga** [comment]
Can we use the ones already provided by `Monad`? such as `replicateM` and `whileM`

**Comment by jdegoes** [comment]
No, since Scalaz IO is soon to be an independent project.

**Comment by wi101** [comment]
Thank you :)

**Pull request merged**
