### PR TITLE
exceptionless number parsing

### PR DESCRIPTION
**Pull request by fommil**
@xuwei-k @NeQuissimus is this something you'd be interested in? I pulled this out of something else I'm working on. I also have benchmarks (it's a lot faster than the stdlib).

I used scalaprops for my tests, that needs to be converted over. I'm not sure I have time to do that and in any case I think scalacheck is not as good as scalaprops.

### CODE REVIEW

**Comment by joroKr21** [comment]
Have you considered using `toIntOption` and co added in Scala 2.13?

**Comment by fommil** [comment]
@joroKr21 I did not know about those things. They look like the do a lot of boxing and they are based on pre-validation before handing off to `java.lang.Double.parseDouble` so they are going to be slower than the stdlib in the general case. Mine are faster for happy and unhappy path.

But perhaps worth letting @martijnhoekstra know about this.

Here's some benchmarks

```
[info] Benchmark                                            Mode  Cnt     Score     Error  Units
[info] SafeNumbersBenchBigDecimal.decodeFommilInvalid      thrpt    5  2959.936 ±  81.822  ops/s
[info] SafeNumbersBenchBigDecimal.decodeFommilUnsafeValid  thrpt    5  2456.022 ±  14.739  ops/s
[info] SafeNumbersBenchBigDecimal.decodeFommilValid        thrpt    5  2327.857 ±  32.860  ops/s
[info] SafeNumbersBenchBigDecimal.decodeStdlibInvalid      thrpt    5   190.482 ±  15.824  ops/s
[info] SafeNumbersBenchBigDecimal.decodeStdlibValid        thrpt    5   875.830 ±   7.229  ops/s
[info] SafeNumbersBenchFloat.decodeFommilInvalid           thrpt    5  2915.608 ± 392.186  ops/s
[info] SafeNumbersBenchFloat.decodeFommilUnsafeValid       thrpt    5  4656.531 ±  32.771  ops/s
[info] SafeNumbersBenchFloat.decodeFommilValid             thrpt    5  4302.962 ±  26.016  ops/s
[info] SafeNumbersBenchFloat.decodeStdlibInvalid           thrpt    5   192.006 ±  20.790  ops/s
[info] SafeNumbersBenchFloat.decodeStdlibValid             thrpt    5  2291.166 ±  13.696  ops/s
[info] SafeNumbersBenchInt.decodeFommilInvalid             thrpt    5  4652.074 ±  31.744  ops/s
[info] SafeNumbersBenchInt.decodeFommilValid               thrpt    5  6812.406 ±  45.588  ops/s
[info] SafeNumbersBenchInt.decodeFommilValidUnsafe         thrpt    5  7806.260 ±  85.288  ops/s
[info] SafeNumbersBenchInt.decodeStdlibInvalid             thrpt    5   208.142 ±  22.707  ops/s
[info] SafeNumbersBenchInt.decodeStdlibValid               thrpt    5  7780.261 ±  75.007  ops/s
```

**Comment by joroKr21** [comment]
Yeah perhaps it's worth benchmarking against stdlib `to*Option` versions and consider contributing directly to stdlib.

**Comment by fommil** [comment]
@joroKr21 I'll contribute my free time to the stdlib over my dead body.

**Comment by fommil** [comment]
@joroKr21 it's more or less what could have been expected. Scala 2.13 optimises for the unhappy path and loses out on the happy path. I didn't check for agreement on the numbers and scala doesn't provide a Big* variant.

```
[info] Benchmark                                            Mode  Cnt      Score    Error  Units
[info] SafeNumbersBenchBigDecimal.decodeFommilInvalid      thrpt    5   2893.473 ± 71.772  ops/s
[info] SafeNumbersBenchBigDecimal.decodeFommilUnsafeValid  thrpt    5   2336.651 ±  8.160  ops/s
[info] SafeNumbersBenchBigDecimal.decodeFommilValid        thrpt    5   2307.544 ± 14.938  ops/s
[info] SafeNumbersBenchBigDecimal.decodeStdlibInvalid      thrpt    5    191.153 ± 19.192  ops/s
[info] SafeNumbersBenchBigDecimal.decodeStdlibValid        thrpt    5    877.875 ±  4.158  ops/s
[info] SafeNumbersBenchFloat.decodeFommilInvalid           thrpt    5   2951.598 ± 65.632  ops/s
[info] SafeNumbersBenchFloat.decodeFommilUnsafeValid       thrpt    5   4326.105 ± 24.620  ops/s
[info] SafeNumbersBenchFloat.decodeFommilValid             thrpt    5   4078.772 ± 18.642  ops/s
[info] SafeNumbersBenchFloat.decodeScala213Invalid         thrpt    5  18066.153 ± 82.201  ops/s
[info] SafeNumbersBenchFloat.decodeScala213Valid           thrpt    5   1868.414 ±  5.999  ops/s
[info] SafeNumbersBenchFloat.decodeStdlibInvalid           thrpt    5    192.643 ± 19.947  ops/s
[info] SafeNumbersBenchFloat.decodeStdlibValid             thrpt    5   2255.965 ± 11.327  ops/s
[info] SafeNumbersBenchInt.decodeFommilInvalid             thrpt    5   4651.250 ± 20.931  ops/s
[info] SafeNumbersBenchInt.decodeFommilValid               thrpt    5   6812.677 ± 38.288  ops/s
[info] SafeNumbersBenchInt.decodeFommilValidUnsafe         thrpt    5   7747.447 ± 94.377  ops/s
[info] SafeNumbersBenchInt.decodeScala213Invalid           thrpt    5   9147.868 ± 51.399  ops/s
[info] SafeNumbersBenchInt.decodeScala213Valid             thrpt    5   6989.627 ± 39.738  ops/s
[info] SafeNumbersBenchInt.decodeStdlibInvalid             thrpt    5    212.592 ± 31.398  ops/s
[info] SafeNumbersBenchInt.decodeStdlibValid               thrpt    5   7791.804 ± 23.075  ops/s
```

**Comment by joroKr21** [comment]
Tradeoffs everywhere 🤔

**Comment by martijnhoekstra** [comment]
I would expect toShortOption, toIntOption and toLongOption to be fast for the happy and unhappy path both, as they're a full re-implementation of parsing. toFloatOption and toDoubleOption do a pre-check and then a hand-off and a implementation of those would handily beat them out.

They could be made a few percentage points faster yet if they don't have to agree with Java, but only consider 0-f numbers, which has a significant impact. It's the price for being able to do `"౨5".toIntOption == Some(25)`

Property-based testing in the stdlib is in the scalacheck library.

**Comment by fommil** [comment]
@martijnhoekstra ah, yes, I see it now. Yeah it looks like your fixed precision integer parsing is more or less equivalent to mine.

If Scalaz wants to just support scala 2.13+ then it sounds like using the scala stdlib byte/short/int/long parser is probably ok (since Validation causes boxing anyway) and then just use SafeNumbers for BigInteger / BigDecimal / double / float.

**Comment by fommil** [comment]
closed due to lack of interest.

**Pull request closed without merging**
