### PR TITLE
workaround for https://github.com/scala-native/scala-native/issues/562

### PR DESCRIPTION
**Pull request by xuwei-k**
- https://twitter.com/jb9i/status/838401563504820225
- https://github.com/scala-native/scala-native/issues/562
- https://github.com/scala/community-builds/issues/500

/cc @SethTisue @densh @MasseGuillaume @jbgi

### CODE REVIEW

**Comment by SethTisue** [comment]
@xuwei-k would it be difficult to backport this to series/7.2.x? that's the branch we track in the Scala 2.12 community build.

**Comment by aloiscochard** [comment]
@SethTisue is there any strong reason not to track `series/7.3.x` in the community build instead?

**Comment by xuwei-k** [comment]
@SethTisue backported https://github.com/scalaz/scalaz/commit/3318a7935c598957207acf5c3381b14b51e0f8aa

**Comment by SethTisue** [comment]
> is there any strong reason not to track series/7.3.x in the community build instead

let's discuss or at least track at https://github.com/scala/community-builds/issues/515

**Pull request merged**
