### PR TITLE
Consistent map#2051

### PR DESCRIPTION
**Pull request by GodPlaysChess**
consistent api for `==>>` according to this issue: https://github.com/scalaz/scalaz/issues/2051
Some tests will be cleaned up as soon as  `Foldable` and `IList` will be consistent

### CODE REVIEW

**Comment by TomasMikula** [comment]
Sorry for the delay. Can you please resolve conflicts and rebase?

**Comment by GodPlaysChess** [comment]
Oh, sorry, my bad. I though I did it.
Will do it asap.

**Comment by TomasMikula** [comment]
This PR shows a lot of unrelated commits. You probably rebased those commits so Git does not recognize them as already present in `series/7.3.x`.

**Comment by GodPlaysChess** [comment]
I'll create a new branch then and cherry pick the related ones against series/7.3.x

**Comment by TomasMikula** [comment]
Superseded by #2061

**Pull request closed without merging**
