### PR TITLE
Add generic zipWithIndex to Traverse syntax

### PR DESCRIPTION
**Pull request by puffnfresh**

### CODE REVIEW

**Comment by tonymorris** [comment]
Maybe name it something else so as not to clash with stdlib? Torn.

**Comment by puffnfresh** [comment]
I'm mostly concerned with structures which do not provide it, although this might provide it better.

**Comment by jedws** [comment]
won't structures that do provide it already directly simply use the one they provide? Ie. you couldn't use this syntax to call the `Traverse` provided `zipWithIndex`, but would you want to?

**Comment by puffnfresh** [comment]
@jedws yes, and so you get ridiculous shit like this:

```
scala> (Some(1): Option[Int]).zipWithIndex
res0: Iterable[(Int, Int)] = List((1,0))
```

Instead of something working.

I think I'm on the side of changing the name.

**Comment by puffnfresh** [comment]
Also, it looks like I've flipped `zipWithIndex` when compared to the convention in stdlib.

**Comment by tonymorris** [comment]
Yeah, the problem is when the stdlib takes the name and does something silly with it. There is a history of this. I don't know if `zipWithIndex` already does something silly, or plans on it for the future, but I know where my bets are.

It's the real reason that unicode identifier names are a good idea; name things exactly as others would not.

**Comment by xuwei-k** [comment]
:+1: except discussion about name.

**Comment by puffnfresh** [comment]
Re-targeting at 7.3

**Pull request closed without merging**
