### PR TITLE
Backport 7.1

### PR DESCRIPTION
**Pull request by xuwei-k**
It’s about time to release 7.1.1?

### CODE REVIEW

**Comment by jedws** [comment]
what's the backwards-compat tool?

presumably as long as this is all binary compatible with 7.1.0 it should all be good, right?

**Comment by xuwei-k** [comment]
Of course, all commits are binary compatible. using mima https://github.com/scalaz/scalaz/commit/8652afc6441a5e345da3bd

**Comment by jedws** [comment]
nice.

what do you need to progress then?

**Comment by xuwei-k** [comment]
What do you mean? Probably, I cherry-picked all mergeable commits. I think we can merge this pull request and then release 7.1.1 right now.

**Comment by jedws** [comment]
I just meant do you need any help.

+1 to getting it out.

**Comment by xuwei-k** [comment]
thank you.
BTW there is a problem I don't know who have authority to release sonatype.

**Comment by aloiscochard** [comment]
@xuwei-k Hi Kenji, I think for now only @tonymorris have the authority

We had a discussion on IRC recently, and I proposed to try to automate as much as possible so ideally... just creating a tag/branch with a specific name could trigger the release.

In the meantime, I think it would be nice if Tony give you the credentials so you can at least do it manually.

FWIW, I plan to add a job to publish snapshot of 7.2 as well.

(also, +1 for releasing, and thank you for the great work!)

**Comment by tonymorris** [comment]
Which button must be pressed? I've actually not used sonatype before.

**Comment by aloiscochard** [comment]
@xuwei-k could you please create an account on sonatype oss and comment on that issue asking for permissions: 
https://issues.sonatype.org/browse/OSSRH-2732

Please refer to this PR in your comment

**Comment by xuwei-k** [comment]
Thanks! I just commented on sonatype JIRA

**Comment by xuwei-k** [comment]
I gained permission. if there are no objections, I will merge this pull request and release 7.1.1 within a few days.

**Comment by aloiscochard** [comment]
@xuwei-k that is awesome!

Please send an announce on the mailing list when you publish the artifacts, thanks :)

**Comment by puffnfresh** [comment]
@xuwei-k :+1:

**Pull request merged**
