### PR TITLE
fix foldMap stack safety

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/non/cats/pull/702

/cc @runarorama

### CODE REVIEW

**Comment by xuwei-k** [comment]
Oh, maybe this is incorrect https://github.com/non/cats/issues/712

**Comment by jedws** [comment]
can you add a test for that?

**Comment by xuwei-k** [comment]
I think we should use [this technique](https://github.com/scalaz/scalaz/commit/d76c426b2b921129693a1) again.

**Comment by xuwei-k** [comment]
I will send another pull request.

**Pull request closed without merging**
