### PR TITLE
remove RightProjection/LeftProjection instances

### PR DESCRIPTION
**Pull request by xuwei-k**
https://github.com/scala/scala/commit/6e9faf5157132ad575c98e5a9a0919ac38b7beb8

### CODE REVIEW

**Comment by tonymorris** [comment]
Do they cause problems?

**Comment by puffnfresh** [comment]
Looks like they'll be deprecated in 2.12

**Comment by tonymorris** [comment]
Full circle!

**Comment by xuwei-k** [comment]
> Looks like they'll be deprecated in 2.12

:confused: https://github.com/scala/scala/pull/5433

**Pull request merged**
