### PR TITLE
Mention IRC channel, google group in README

### PR DESCRIPTION
**Pull request by S11001001**
Addresses #1369.

### CODE REVIEW

**Comment by tonymorris** [comment]
I think the IRC link should have at least `irc://irc.freenode.net/#scalaz` and then perhaps a second link to webchat. Some client software follows the `irc://` links to open a IRC client.

**Comment by S11001001** [comment]
@tonymorris As you say.

**Comment by S11001001** [comment]
@tonymorris Looks like Github won't render irc: links.

**Comment by tonymorris** [comment]
Cheers big ears. Also, yes I just remembered that github schmithub won't render irc links.

:+1:

**Comment by TomasMikula** [comment]
👍

**Pull request merged**
