### PR TITLE
Disjunctions example 1374

### PR DESCRIPTION
**Pull request by abhishek7**
Simple example using `\/` in Scalaz, referencing https://github.com/scalaz/scalaz/issues/1374. Happy to update this as time goes on, or if there is anything in particular we'd like to see prior to merging.

### CODE REVIEW

**Comment by TomasMikula** [comment]
I don't think we should document standard Scala syntax, such as infix notation for symbolic names.

Things that _might_ be worth demoing:
 - creating a value of `A \/ B`;
 - pattern matching on `A \/ B`;
 - right biased functor instance;
 - ???

I would also avoid writing in comments that which is clear from the code.

**Comment by abhishek7** [comment]
Thanks for the comments, will update the PR with the three things you proposed. It may or may not be worth having as a demo, but if I think of anything else while working on this, I'll add it on.

**Comment by abhishek7** [comment]
@TomasMikula I'm trying to add on some examples around right biased functor instances now. Could you please explain what that is? I was doing some research on my own about this, but I haven't found anything useful yet. Please let me know if there are any resources I can refer to.

**Comment by TomasMikula** [comment]
@puffnfresh 

> `\/.left` and `\/.right` should be used, not the Scala constructors.

After #1645, this should not matter. `-\/` and `\/-` smart constructors now return `\/`.

**Comment by abhishek7** [comment]
@TomasMikula, are there any examples I can refer to for a right-biased functor instance? I asked a question a while back about this here: https://stackoverflow.com/questions/48738404/what-is-functor-bias, but the concept is still a bit unclear to me.

**Comment by JordanMartinez** [comment]
@abhishek7 Given the following object
````scala
case class Box[A] (value: A) {}
````
a Functor will "open" the box, pass the `value` into a function `(A => B)` and put the result of the function into a new Box (`Box[B]`). There is no confusion as to which "value" to pass into the function because the `Box` type only has one possible value that could be passed into the function: `value`

Now, let's say we have a new data class:
````scala
case class Box2[A, B] (valueA: A, valueB: B) {}
````
If we wanted to use a `Functor` on `Box2[A, B]`, should we output `Box2[C, B]` or `Box2[A, C]` since we can only map one of the values? In other words, should we pass `valueA` into a function `(A => C)`? Or should we pass `valueB` into a function `(B => C)`?

A right-biased Functor means we should output `Box2[A, C]` by passing `valueB` into the function `(B => C)`. A left-biased Functor would take the opposite route: output `Box2[C, B] with `valueA` passed into the function (`A => C)`. The bias refers to which of the two types we should use in a function.

Does the answer to your StackOverflow question now make more sense? Given an `Either[A, B]`, which "value" do we pass into the function, the value stored in the `Left[A]` or the value stored in the `Right[B]`? Since an `Either` is usually used to distinguish between an error (the left side) and a correct value (the right side), we typically only want to map the `Either` when the instance is `Right[B]`. Hence, `Either` is a right-biased functor.

Returning to `Box2[A, B]`, if we wanted to map both values at once so that `Box[C, D] is outputted with functions `(A => C)` and `(B => D)`, we would use a `BiFunctor`.

**Comment by TomasMikula** [comment]
@abhishek7 Yeah, this jargon is not very precise.

It doesn't make sense to say that `Either` is a functor, because it doesn't have the right shape. It makes sense to ask whether `Either[A, ?]` is a functor (for any fixed type `A`) or whether `Either[?, B]` is a functor (for any fixed type `B`). The answer is yes in both cases. Once we set our mind to a type constructor of the correct shape (`Either[A, ?]` or `Either[?, B]`), the functor instance for it has no bias. The bias is only in _our preference_ for the former, i.e. `Functor[Either[A, ?]]`, because that's the more common use case (as noted by @JordanMartinez), and also because it works better with type inference (namely with partial unification, which is also "right biased"). Other than that, `Functor[Either[A, ?]]` and `Functor[Either[?, B]]` are equally good functors. We don't provide both implicitly because it would confuse type inference in some situations. So we choose to provide the one that we _usually_ want and that one also plays better with type inference.

**Comment by abhishek7** [comment]
@JordanMartinez @TomasMikula excellent explanations, thank you, I appreciate it! This makes much more sense now.

**Comment by abhishek7** [comment]
@TomasMikula @JordanMartinez @puffnfresh @S11001001 Please take a look at the new PR when you can: https://github.com/scalaz/scalaz/pull/1822

**Pull request closed without merging**
