### PR TITLE
Make tree construction and pattern matching more consistent.

### PR DESCRIPTION
**Pull request by shawjef3**
Right now, you create trees with "def node", "def leaf", or the apply method of Tree. However, you pattern match, but do not create trees with Tree.Node. This is very inconsistent with how Scala construction and pattern matching usually work. Normally you have a capital letter object that you can use for both construction and pattern matching.

Changing Node to fit what I would normally expect from a Scala object is pretty easy; just add apply. Then as an analog of the leaf method, add a Leaf object with apply and unapply, so that pattern matching and construction is more like a normal Scala case class.

Tree.apply is completely weird. It actually is for creating a leaf, not a tree, and there's no corresponding unapply. I think that method should be deprecated or changed to create a node instead of a leaf, but that's another ticket.

Jeff

### CODE REVIEW

**Comment by S11001001** [comment]
:+1:

Also :+1: to deprecating Tree.apply and Tree.unapply and changing all their callers.

**Comment by jedws** [comment]
+1 for the change and @shawjef3 please deprecate the Tree.apply/unapply as well.

**Comment by xuwei-k** [comment]
:+1: 
however `scalaz-seven` is not main branch. 

https://github.com/scalaz/scalaz/commit/824b27797d26ba466edd7430748cc40e
> This branch has been discontinued and is kept for historical purposes. Development continues on the appropriate release branches:

please send to `series/7.2.x`

**Comment by shawjef3** [comment]
Reopened as #1031.

**Pull request closed without merging**
