### PR TITLE
[7.2.x] support scala-js

### PR DESCRIPTION
**Pull request by xuwei-k**
I will send another pull request to `series/7.3.x` branch.

https://github.com/scalaz/scalaz/issues/1062

### CODE REVIEW

**Comment by japgolly** [comment]
Oh :/ I was working on this yesterday too. 

7.3 working is working over here: https://github.com/japgolly/scalaz/tree/scalajs-7.3-wip
In fact it's done, just need to squash commits. Only thing is I couldn't get stupid Travis to pass.

**Comment by japgolly** [comment]
Nice changes to the SBT build and travis.yml, @xuwei-k. Did you base this on my 7.2 branch?

**Comment by xuwei-k** [comment]
> Did you base this on my 7.2 branch?

Yeah, Thanks for your contributions :)

**Comment by japgolly** [comment]
Yay, I'm glad all that time wasn't wasted :)

I also did 7.3 yesterday, you can see on my branch if it will help. You did a much better job at SBT & Travis so probably only the java8 time stuff will be of interest.

**Pull request merged**
