### PR TITLE
Optimize performance by avoiding lazy val

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by xuwei-k** [comment]
Could you explain your intention? I disagree with this changes. I think these value should be _call by need_

**Comment by Atry** [comment]
There is no reason to cache the `ifTrue` and `isFalse` parts. They usually don't evaluate again.

**Comment by Atry** [comment]
The cache behavior yields more terrible case for `while`, https://github.com/scalaz/scalaz/issues/940

**Comment by S11001001** [comment]
They do evaluate again often for List et al.

**Comment by Atry** [comment]
@S11001001 No, they didn't.

```
scala> Monad[List].ifM(List(true, false, true, false), Monad[List].pure { println("ifTrue") }, Monad[List].pure { println("ifFalse") })
ifTrue
ifFalse
res3: List[Unit] = List((), (), (), ())
```

**Comment by S11001001** [comment]
It shouldn't.

**Comment by aloiscochard** [comment]
:-1: that is not the behavior I would expect.

**Pull request closed without merging**
