### PR TITLE
mproduct combinator in Bind

### PR DESCRIPTION
**Pull request by wedens**
`fproduct` like combinator on a Monad. If somebody can suggest better name, I'm open to suggestions :)

### CODE REVIEW

**Comment by xuwei-k** [comment]
Could you move to `Bind` from `Monad`? because this method does not requires `Monad#point`.  Furthermore could you add `BindOps#mproduct` ?

**Comment by wedens** [comment]
@xuwei-k done

**Comment by aloiscochard** [comment]
:+1: 

I like that name and I don't see a better one, but if someone else have suggestions...

(Nitpick: The commits could be squashed)

**Comment by wedens** [comment]
@aloiscochard policies on rebasing PRs varies from project to project :)

**Comment by aloiscochard** [comment]
@wedens Sorry if I make it sound like I was trying to enforce a policy!

I tried to emphasis it was really just a remark by using parenthesis and "nitpick", which basically mean "Just ignore me if you want to" ;)

**Comment by xuwei-k** [comment]
:+1:

**Pull request merged**
